CodeSystem: COVID19UnderlyingConditionCategoryCS
Id: covid19-underlying-condition-category-cs
Title: "COVID19 Underlying Condition Category Code System"
Description: "A set of types of underlying condition categories."
* #MEDCOND "COVID19 Underlying Medical Condition"
* #CARCOND "COVID19 Underlying Cardiovascular Condition"
* #NEUROCOND "COVID19 Underlying Neurologic Condition"
* #IMMUNOCOND "COVID19 Underlying Immunocompromised Condition"
* #RESCOND "COVID19 Underlying Respiratory Condition"
* #METCOND "COVID19 Underlying Metabolic Condition"
* #HEMCOND "COVID19 Underlying Hemoglobinopathy Condition"
* #RENCOND "COVID19 Underlying Renal Condition"
* #IMMCOND "COVID19 Underlying Immune Condition"
* #GSHCOND "COVID19 Underlying Gastrointestinal or Hepatic Condition"
* #UNCCOND "COVID19 Underlying Uncategorized Condition"
